### ISSUE TITLE
The thread unsafe operation

### ISSUE THREAD

**Issue by voltento** [opentracing/opentracing-cpp#121]
https://github.com/opentracing/opentracing-cpp/blob/4bb431f7728eaf383a07e86f9754a5b67575dab0/src/tracer.cpp#L20

The operator swap for std::shared_ptr<> doesn't look like thread safe - http://www.cplusplus.com/reference/memory/shared_ptr/swap-free/
Probably you should use the std::atomic_exchange or std::atomic_store method to make this code thread safe - https://en.cppreference.com/w/cpp/atomic/atomic_exchange

**Comment by rnburn** [comment]
It uses a [mutex](https://github.com/opentracing/opentracing-cpp/blob/4bb431f7728eaf383a07e86f9754a5b67575dab0/src/tracer.cpp#L18) to ensure it's not called from multiple threads.

The [versions](https://github.com/opentracing/opentracing-cpp/blob/4bb431f7728eaf383a07e86f9754a5b67575dab0/src/tracer.cpp#L18) of those atomic functions that work for std::shared_ptr aren't supported in gcc-4.8
