### ISSUE TITLE
CPU overhead of instrumented code

### ISSUE THREAD

**Issue by f-squirrel** [opentracing/opentracing-cpp#127]
I'd like to know if there is any information/benchmark about the overhead of tracing?

**Comment by rnburn** [comment]
The opentracing-repo is just an API. The overhead will depend on the tracer implementation.

But there's some benchmarking data available for lightstep's tracer
cpu overhead: https://217-55084842-gh.circle-artifacts.com/0/graphs/cpp_sps_vs_cpu.png
times for different [operations](https://github.com/lightstep/lightstep-tracer-cpp/blob/master/benchmark/span_operations_benchmark.cpp): https://7739-57146219-gh.circle-artifacts.com/0/benchmark/span_operations_benchmark_result.txt
