### ISSUE TITLE
Provide some links to tracing implementations

### ISSUE THREAD

**Issue by xd009642** [opentracing/opentracing-cpp#130]
The mock_tracer and the readme examples of `some_tracing_impl.h` are fine for conceptually showing the library but there should be links or an easy way to find actual tracing implementations that can be used and demonstration of this in the examples. i.e. where would I find tracing for opencensus/opentelemetry/jaeger?

**Comment by yurishkuro** [comment]
in the standard place: https://opentracing.io/registry

**Comment by xd009642** [comment]
Okay so as this is the only c++ one https://github.com/opentracing-contrib/cpp-grpc I'm guessing this project isn't ready for use in c++ unless I implement the tracer myself. Unless there's any less official ones

**Comment by yurishkuro** [comment]
Jaeger has a CPP client https://github.com/jaegertracing/jaeger-client-cpp

**Comment by yurishkuro** [comment]
btw, the registry wasn't recognizing `c++` query, so I just fixed the tags: https://opentracing.io/registry/?s=cpp

**Comment by xd009642** [comment]
hmm I tried jaeger-client-cpp before but there were build issues I couldn't get around that seemed to be caused by hunter... It's a bit disappointing that setting up tracing in my Go and Rust services is a breeze but C++ doesn't seem to be fully there yet :cry: that's for the help though
