### ISSUE TITLE
Use of string_view in StartSpanOption::tags is dangerous

### ISSUE THREAD

**Issue by pantoss** [opentracing/opentracing-cpp#17]
`#include <iostream>
#include <opentracing/tracer.h>
#include <opentracing/tracer.h>

using namespace std;
using namespace opentracing;

void SetStandardOptions(StartSpanOptions& options)
{
    {
        string mystring = "user_agent";
        opentracing::SetTag o1 = opentracing::SetTag{mystring, "test1"};
        o1.Apply(options);
    }
    {
        string mystring = "blah";
        opentracing::SetTag o1 = opentracing::SetTag{mystring, "test2"};
        o1.Apply(options);
    }
}

void PrintOptions(StartSpanOptions& options)
{
    string test = "someString1";
    string test2 = "someString2";
    for (auto a : options.tags)
    {
        cout << a.first << endl;
    }
}

int main()
{
    StartSpanOptions options;
    SetStandardOptions(options);
    PrintOptions(options);
    return 0;
}`

Output should be:
user_agent
blah

I get:
&@��P�L
&@��

This is due to the tags storing the string_view instead of a copy of the string.

I don't really understand the purpose of using string_view throughout the API. I would love to know the reasoning? I don't see any performance benefit to using over passing a string by reference. You might be able to get some improvement though the use of move semantics but in all likelihood all the strings will be small enough to avoid the free store anyway.

**Comment by rnburn** [comment]
Yes, StartSpanOptions isn't meant to be used like that.

string_view is more efficient because not everything stores character sequences as std::string's. (See for example the instrumentation [nginx](https://github.com/rnburn/nginx-opentracing) or any other c library). It's also quite common to use sting literals where string_view allows you to avoid construction of an std::string object. See [here](https://stackoverflow.com/questions/40127965/how-exactly-stdstring-view-is-faster-than-const-stdstring) if you want a full list of examples.

**Comment by pantoss** [comment]
Can I suggest that string_view unary constructor from a string is made explicit or removed as it has been in std::string_view? This would make it more apparent to the user of the api but still support the most common use case where a string literal is behind passed in.

**Comment by rnburn** [comment]
std::string is meant to be [implicitly convertible](https://wandbox.org/permlink/00ehRwPf60EAfwtJ) to std::string_view. 

std::string_view doesn't have that constructor because there's a [conversion operator](http://en.cppreference.com/w/cpp/string/basic_string/operator_basic_string_view) on std::string.

**Comment by pantoss** [comment]
Oh, I didn't realise that. I saw that the implicit constructor has been moved from the string_view and made the assumption it was to make sure it had to be explicit. (you don't know why they removed it, and made it a conversion operator?).

Is this to make the noop tracer faster?

The reason I saw this was because I was having a go at implementing the interface and I wanted to just move the tags from the StartSpanOptions object into another object for processing later. I suspect this is what most implementations will want to do. At least they will need to create copies of the tags anyway. Obviously I cannot if they are string_views because I don't know if the tags are going to live as long as the span will. The zipkin implementation I've seen does just this, so it has to do more work as far as I can see in most cases and you have the possibility of errors happening due to the unaware using it incorrectly.

I did a quick and dirty test to see what the performance difference was:
`template <typename T, typename T2>
void SetStandardOptions(T2& options)
{
    // I would guess 6 is a little on the higher side for the number of tags.
    for (int i = 0; i< 4; ++i)
    {
        auto o1 = T{"user_agent", "test1"};
        o1.Apply(options);
    }
}

int main()
{
    auto t1 = [](){
    auto s1 = std::chrono::high_resolution_clock::now();
    for (auto i = 0; i < 1000000; ++i)
    {
        StartSpanOptionsStringView options;
        SetStandardOptions<SetTagStringView>(options);
    }
    auto s2 = std::chrono::high_resolution_clock::now();
    for (auto i = 0; i < 1000000; ++i)
    {
        StartSpanOptionsString options;
        SetStandardOptions<SetTagString>(options);
    }
    auto e2 = std::chrono::high_resolution_clock::now();
        auto string_view_d =  static_cast<double>((s2 - s1).count());
        auto string_d =  static_cast<double>((e2 - s2).count());
        double diff_perc  = (1.0-(string_d/string_view_d))*100.0;
        cout << "Noop: " << diff_perc << endl;
    };

    auto t2 = [](){
        auto s1 = std::chrono::high_resolution_clock::now();
        for (auto i = 0; i < 100000; ++i)
        {
            StartSpanOptionsStringView options;
            SetStandardOptions<SetTagStringView>(options);
            vector<pair<string, Value>> tags(options.tags.begin(), options.tags.end());
        }
        auto s2 = std::chrono::high_resolution_clock::now();
        for (auto i = 0; i < 100000; ++i)
        {
            StartSpanOptionsString options;
            SetStandardOptions<SetTagString>(options);
            vector<pair<string, Value>> tags(std::move(options.tags));
        }
        auto e2 = std::chrono::high_resolution_clock::now();
        auto string_view_d =  static_cast<double>((s2 - s1).count());
        auto string_d =  static_cast<double>((e2 - s2).count());
        double diff_perc  = (1.0-(string_d/string_view_d))*100.0;
        cout << "Copies tags: " << diff_perc << endl;
    };
    for (int i = 0; i < 6; ++i)
    {
        t1();
        t2();
    }
    return 0;
}`

Ignoring the first due to caching effects.
Noop: -14.5767
Copies tags: 27.2606
Noop: -16.6628
Copies tags: 25.2908
Noop: -10.7711
Copies tags: 18.595
Noop: -17.12
Copies tags: 25.3837
Noop: -19.5725
Copies tags: 28.4645

And in the case of a Noop, if you are that sensitive to latency, you would be better off just not calling the API in the first place, if you don't want to do tracing or possibly caching the span options before hand.

There are a lot of variables which effects the results however:
Depend on the number of tags you have per span. I don't know what an average number of tags is. I found that the break even point was about 20 tags per span.
The length of your tag. If they are under the SSO limit also makes a significant difference too.
If your tags are char* or strings will make a difference too.

As this is an API I would argue that it should be safer over speed. If the use needs speed they can always work around the API where as you cannot make people know they have incorrect assumptions.

Anyway, I'll just work around it in my case.

**Comment by rnburn** [comment]
I think [this](https://stackoverflow.com/a/39208704) is why it was removed.

string_view isn't meant to eliminate string copies; it's just meant to reduce them. If `SetTag` took a `const std::string&` as an argument instead of `std::string_view`, then calling
```
span.SetTag("abc", 123);
```
would result in two copies instead of one.

But I'm ok changing it to `std::string` in `StartSpanOptions`. I can see how it might not handle dynamically generated tag keys well.

**Comment by rnburn** [comment]
Changed in #19
