### ISSUE TITLE
Virtual hierarchy

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#22]
I have encountered a handful of issues in my attempt to implement the opentracing-cpp API for my Jaeger C++ client (https://github.com/isaachier/cpp-client).

First, I have found that the only way to do type checking is dynamic casting. I am convinced this is not ideal for any C++ class hierarchy. I wonder what other solution there might be for identifying subclasses at runtime. Perhaps a visitor pattern would be more appropriate (i.e. add a virtual visit method to `Span` etc.).

Second, I noticed many virtual methods are declared `const` and `noexcept`. In my experience, this tends to look good upfront, but the implementations will struggle to maintain these guarantees.

Third, related to the second point, is that the `const`-ness seems to be incorrect in a number of situations. For example, the readers and writers in `propagation.h` should not use `const` methods for reading and writing. Why would I want to modify a `const` Reader/Writer by allowing client to change the seek position in the input/output stream? Also, I find `Inject`, `Extract`, and especially `StartSpanWithOptions` are difficult to implement in the Tracer without sacrificing a good deal of `const` correctness.

I'd say you can probably replace the `const`-ness of the virtual methods without sacrificing much backwards-compatibility, but there is no perfect solution. Please let me know what you think.

**Comment by yurishkuro** [comment]
I would suggest splitting these into separate issues and showing concrete code examples illustrating the problems.

**Comment by isaachier** [comment]
Makes sense. Will reopen as split issues soon.
