### ISSUE TITLE
Virtual `const`/`noexcept` methods

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#24]
I am having trouble with the fact that many of the virtual methods force the implementation to be `const` and/or `noexcept`. For example, I would like all of my spans to have a reference to the tracer so they can report when they are finished. Simply, this could be implemented like so

```
class Tracer : public opentracing::Tracer {
    // ...
    void StartSpanWithOptions(opentracing::string_view operationName,
                         const opentracing::StartSpanOptions& options) const noexcept override
    {
        return Span(*this, operationName, options);
    }

    void reportSpan(const Span& span);
};

class Span : public opentracing::Span {
    // ...
    Span(Tracer& tracer, opentracing::string_view operationName, const opentracing::StartSpanOptions& options)
        : _tracer(tracer)
    {
    }

    void FinishWithOptions(const opentracing::FinishSpanOptions& finishSpanOptions) noexcept override
    {
        // Finish span
        _tracer.reportSpan(*this);

        // Parenthetically, this would not work in the header without introducing a cyclic dependency
        // between Tracer and Span, but illustrates the point regardless of the actual location of
        // this code.
    }

    // ...
    Tracer& _tracer;
};
```

However, the above does not work, because the type of the tracer reference passed to the span is `const Tracer& tracer`. The reason being that `Tracer::StartSpanWithOptions` is `const` when it need not be. This forces me into the awkward position of deciding between using `const_cast`ing the reference to the tracer, or making `reportSpan` a `const` method when it logically should not be called on a `const Tracer` object.

**Comment by isaachier** [comment]
I have no urgent feelings regarding `noexcept`, but thought I'd mention it definitely imposes a strict requirement on implementations for no discernible reason. I think it is valid to throw an exception in the case of emitting a span, for example, if the tracer implementation uses an upper bound on the max number of calls per second, etc.

**Comment by yurishkuro** [comment]
Why would you want a monitoring tool to throw exception and potentially disrupt the main app flow? Exceptional situations need to be handled by the library internally. For things like not being able to report spans fast enough we can use metrics. For non-operational problems like the wrong target host:port, logging the error is ok.

**Comment by isaachier** [comment]
OK I guess I get that. I'm still not sure why it is so pervasive, but maybe that justifies the functions in `Tracer`.

**Comment by rnburn** [comment]
@isaachier Just another note on noexcept -- Many of the OpenTracing methods are things a user could want to call from a destructor, which are [noexcept](https://stackoverflow.com/questions/32956339/transitioning-to-c11-where-destructors-are-implicitly-declared-with-noexcept) by default. Allowing methods to throw exceptions would either cause user code within destructors to call [std::terminate](https://en.cppreference.com/w/cpp/error/terminate) or force users to wrap all the tracing code in try/catch blocks.

Given that an application's functioning shouldn't be dependent on tracing working, I think the best thing to do is to handle the exceptions in the tracer by catching, logging, and dropping tags, log records, spans, etc.

**Comment by isaachier** [comment]
OK cool. About logging, are we just assuming stdout/stderr? There is no standard library for C++ logging and this implementation seems to avoid the topic altogether (except the remote logging in spans).

**Comment by rnburn** [comment]
In the LightStep tracer, we initially used spdlog, but then changed it do custom logging to avoid the added dependency and we defaulted to `std::cerr`, but allowed users to optionally [capture](https://github.com/lightstep/lightstep-tracer-cpp/blob/master/include/lightstep/tracer.h#L74) and handle the log themselves.

But, yes, the OT standard doesn't specify anything about logging.

**Comment by yurishkuro** [comment]
> In the LightStep tracer, we initially used spdlog, but then changed it do custom logging

we used a simple custom logging interface in Jaeger as well, in several languages.

**Comment by rnburn** [comment]
A can see the argument for making `StartSpan` non-const. 

I think we missed this when writing the LightStep tracer since we split out the design into a Tracer and Recorder and kept references to the latter as non-const.

**Comment by isaachier** [comment]
OK no big deal. I can do some "hack," probably making the `reportSpan` method non-`const`.

Thanks for the advice about logging. I'm using `spdlog` as of now too. But could do something similar to Jaeger's go client if necessary.
