### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#26]
Not sure if this has ever been addressed, but would it make sense to include a C API header? I was going to try and write one for my own client, but realized it probably makes more sense to wrap the OpenTracing API than my own custom API. Just to reference an example of what I mean, see LevelDB's C header in [c.h](https://github.com/google/leveldb/blob/master/include/leveldb/c.h). Adding a header like that for the OpenTracing API would simplify writing bindings for C based languages such as Python and Lua.

**Comment by rnburn** [comment]
I agree it would be useful. The issue of an OpenTracing C API has come up a few times on [gitter.im/opentracing-cpp](https://gitter.im/opentracing/opentracing-cpp) and there were some people interested (@heyleke).

I think the plan was to define an OT C API in a separate repository and include some sort of bridge from the C++11. I don't think anyone was against such an API -- it's just that nobody has done the work of proposing one yet.

**Comment by isaachier** [comment]
OK great. I may follow up on this with a proposal when I have the time.

**Comment by isaachier** [comment]
It's been a while, but I think I'm almost ready to submit a proposal for a C OpenTracing API. Any ideas where to submit this? I don't think opentracing-c exists yet. Here is the link for now: [opentracing-c](https://github.com/isaachier/opentracing-c).

**Comment by yurishkuro** [comment]
If people think it will be easier to discuss as a PR, I can create an official repo.

One immediate question I have:

```c
typedef struct opentracing_tracer {
    opentracing_span* (*start_span)(struct opentracing_tracer* tracer,
                                    const char* operation_name);
```

This looks like you're pretending to have an "object with methods" - is this a usual practice in C? Any other projects use this technique?

**Comment by isaachier** [comment]
Ya to be fair these aren't truly methods because I'm passing the instance as the first argument each time. The C compiler just sees these as struct members that happen to be function pointers. Go structs do this too from time to time, but C has to use it exclusively. I think I first saw this in the CPython implementation but it's in [libevent](https://github.com/libevent/libevent/blob/master/include/event2/http_struct.h#L122)as well.

What I definitely saw first in CPython was the notion of implementing and interface by making it the first member of the derived struct (see https://github.com/python/cpython/blob/master/Include/object.h#L101). Since opentracing is heavy on interfaces, both techniques are used quite a bit.

**Comment by mikz** [comment]
It is quite a pity there is no C API. 

We are looking at this project, because we would like to interact with OpenTracing from Lua within OpenResty using the nginx-opentracing module. 

I don't get why to reimplement the opentracing library in every language, when it could be just C interface and other implementations just using it. The huge benefit of writing reusable library in low level language is that it can be used as C library from plenty of other places.

It does not need to go to the full extend of parsing http headers from a stream, but it could just implement APIs to manipulate spans, expose tracing ids etc., but leave the details to the implementation.

**Comment by isaachier** [comment]
I agree @mikz about the bindings and hopefully this is a good starting point. I'm hoping this actually allows for a complete OpenTracing interface in C despite the inherent difficulties therein.

**Comment by isaachier** [comment]
Think we can close as this seeing as https://github.com/opentracing/opentracing-c exists.
