### ISSUE TITLE
Default construction of `StartSpanOptions` sets timestamps to epoch time

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#29]
Calling `tracer->StartSpan("operation")` intuitively should behave the same as calling `tracer->StartSpanWithOptions("operation", StartSpanOptions())`, however it doesn't. The former default constructs the `StartSpanOptions` object and sets the timestamps to `Clock::now()`, but the latter does not set the timestamps. I think it would make more sense to set the timestamps to `Clock::now()` in a new default constructor `StartSpanOptions()`.

**Comment by yurishkuro** [comment]
+1

options are meant to be optional, you only need to set those that you care about

**Comment by isaachier** [comment]
I literally just wasted a whole day debugging this...

**Comment by rnburn** [comment]
How about just removing these [lines](https://github.com/opentracing/opentracing-cpp/blob/master/include/opentracing/tracer.h#L82-L83). Then the tracers can set the timestamps if `options.start_system_timestamp == std::chrono::system_clock::time_point{}`.

I could see stamping the times in StartSpanOptions default constructor causing an issues if you want to reuse the options or if you construct it significantly before the span. 

It would also match the behavior in [Go](https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L140).

**Comment by yurishkuro** [comment]
makes sense

**Comment by rnburn** [comment]
I put in https://github.com/opentracing/opentracing-cpp/pull/30. I also documented the options more to make the expected behavior clearer. Let me know if that works for you. (Sorry for the trouble).

**Comment by rnburn** [comment]
Updated in #30.
