### ISSUE TITLE
Provide an example for usage of HTTPHeadersReader

### ISSUE THREAD

**Issue by bcherukuri** [opentracing/opentracing-cpp#31]
I am trying to implement how to use `HTTPHeadersReader` especially what to override for following

```
  virtual expected<void> ForeachKey(
      std::function<expected<void>(string_view key, string_view value)> f)
      const = 0;
```

**Comment by rnburn** [comment]
Sure. In the meantime, you can look at what's done [here](https://github.com/rnburn/zipkin-cpp-opentracing/blob/master/zipkin_opentracing/example/text_map_carrier.h#L23).

**Comment by bcherukuri** [comment]
@rnburn can you provide an example on how to read this on thrift/HTTP server?

On server I start service something like this

```
void start_service(const options &options)
{

    // Setup services
    const boost::shared_ptr<TMultiplexedProcessor> processor = boost::make_shared<TMultiplexedProcessor>();

    // config
    auto config = std::make_shared<config>();

    processor->registerProcessor(
        "bar",
        boost::make_shared<bar>(boost::make_shared<bar_impl>(metrics, config)));

    processor->registerProcessor(
        "foobar",
        boost::make_shared<foobar>(boost::make_shared<foobar_impl>()));

    // Setup thread pool
    const int                              workerCount    = std::thread::hardware_concurrency();
    const boost::shared_ptr<ThreadManager> thread_manager = ThreadManager::newSimpleThreadManager(workerCount);
    thread_manager->threadFactory(boost::make_shared<PlatformThreadFactory>());
    thread_manager->start();

    // Start server
    const boost::shared_ptr<TServerTransport>  server_transport  = boost::make_shared<TServerSocket>(options.http_port);
    const boost::shared_ptr<TTransportFactory> transport_factory = boost::make_shared<THttpServerTransportFactory>();
    const boost::shared_ptr<TProtocolFactory>  protocol_factory  = boost::make_shared<TBinaryProtocolFactory>();

    TThreadPoolServer server(processor, server_transport, transport_factory, protocol_factory, thread_manager);

    hub_info_stream("Starting service at port: " << options.http_port);

    server.serve();
}

```

**Comment by rnburn** [comment]
You can look at how it was done in java: [opentracing-contrib/java-thrift](https://github.com/opentracing-contrib/java-thrift).

I don't know that thrift gives you access to the headers in a way allows you to instrument with only a simple carrier class.

**Comment by bcherukuri** [comment]
+Nikhil Murarka <nmurarka@uber.com> +Larry Spector <lspector@uber.com> +Isaac
Hier <ihier@uber.com>

One thing I am not able to understand here is, how thrift methods can
access the "Span" so that it can pass along to other dependent services.

In following example I do not see any way of extracting span inside thrift
methods. For example "Say"

https://github.com/opentracing-contrib/java-thrift/blob/master/src/test/java/io/opentracing/thrift/CustomHandler.java

**Comment by bcherukuri** [comment]
One more thing is, I could not find "ThreadLocalActiveSpanSource" C++ version, we do have "Thread Local Storage" in POSIX threads.

https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/ThreadLocalActiveSpanSource.java

**Comment by isaachier** [comment]
@bcherukuri the only way the Thrift client can decode spans is by passing all the received headers to the Tracer implementation. That is why there are interfaces (i.e. `HTTPHeaderReader`) in `propagation.h` for you to implement in one of your own classes.

**Comment by isaachier** [comment]
Thread local storage might be useful but isn't strictly necessary for the tracing standard to be complete.

**Comment by isaachier** [comment]
@bcherukuri here is a full implementation example assuming a client with headers.

```
    class HTTPClient : public opentracing::HTTPHeadersReader {
      public:
        opentracing::expected<void> ForeachKey(
            std::function<expected<void>(opentracing::string_view, opentracing::string_view)> f) const override
        {
            for (auto&& headerPair : _headerMap) {
                f(headerPair.first, headerPair.second);
            }
        }

      private:
        std::unordered_map<std::string, std::string> _headerMap;
    };
```

**Comment by rnburn** [comment]
I put in #33 to document Inject/Extract.

@bcherukuri -- if you want more specific help with Thrift instrumentation, the [gitter channel](https://gitter.im/opentracing/public) would be a better place to ask.
