### ISSUE TITLE
Add log function for runtime types

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#35]
As of now, a user must use an initializer list to log key-value pairs. The problem is, this effectively disables any dynamic logging. For example, if I want to log a list of key-value pairs, I have to know this list at compile time, seeing as no STL container can be converted into an initializer list at runtime.

Here are a few ideas for a new log function overload:

```
using Iterator = std::vector<std::pair<string_view, Value>>::const_iterator;
virtual void Log(Iterator first, Iterator last) noexcept = 0;
```

or

```
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by isaachier** [comment]
```
virtual void Log(const std::unordered_map<string_view, Value>& pairs) noexcept = 0;
```

**Comment by rnburn** [comment]
What would you think of adding an overload for something like [LogRecord](https://github.com/opentracing/opentracing-go/blob/master/span.go#L123) that's in the Go API?

 You can use it to customize the timestamp of the log as well.

**Comment by isaachier** [comment]
I'd like that too. TBH, anything other than `std::initializer_list` is fine with me.
