### ISSUE TITLE
Support for sampling priority

### ISSUE THREAD

**Issue by isaachier** [opentracing/opentracing-cpp#38]
Do not find anything in here about sampling priority. I think it should be added, potentially to `Span::SetTag` documentation.

**Comment by yurishkuro** [comment]
it is typical for all OT APIs to provide a set of constants for standard tags and standard logs

https://github.com/opentracing/opentracing-go/blob/master/ext/tags.go
https://github.com/opentracing/opentracing-go/blob/master/log/field.go
