### ISSUE TITLE
Build with -fPIC

### ISSUE THREAD

**Issue by ringerc** [opentracing/opentracing-cpp#49]
Opentracing should really default to building a shared lib with -fPIC (gcc); there's not really any good reason not to build position-indepedent code anymore.

Lack of -fPIC upsets jaeger-cpp among other things.

**Comment by rnburn** [comment]
CMake should automatically set PIC for shared libraries. Are you not seeing this?

Jaeger links to opentracing-cpp statically, which is probably why it's complaining. But you can build with `cmake -DCMAKE_CXX_FLAGS="-fPIC"` to override the static library defaults.

**Comment by isaachier** [comment]
@rnburn I use [CMAKE_POSITION_INDEPENDENT_CODE](https://github.com/jaegertracing/cpp-client/blob/master/cmake/toolchain.cmake#L4) to compile both static and shared libraries with `-fPIC`.

**Comment by ringerc** [comment]
I don't really see any good reason not to build without -fPIC these days, but in any case, that seems like Jaeger doing something weird. It shouldn't be linking to the opentracing static lib for its own shared lib anyway. Will open issue there.

**Comment by ringerc** [comment]
@isaachier That only helps if you let Jaeger build opentracing via its download-everything-from-the-Internet magic. That's not going to fly in the sorts of environments many things like databases deploy in. Otherwise you have to know to build your opentracing that way, and it's currently an undocumented requirement.

More generally, linking to a static lib in a shared lib is a weird thing to do. Is there a compelling reason Jaeger does that?

**Comment by ringerc** [comment]
Workaround: build opentracing with `-DCMAKE_POSITION_INDEPENDENT_CODE=on`

**Comment by isaachier** [comment]
Well this particular setting has nothing to do with Hunter. I'm suggesting @rnburn use this standard cmake setting I used.

**Comment by rnburn** [comment]
@isaachier it's not at all standard to build static libraries with -fPIC.

**Comment by isaachier** [comment]
I don't mean it is standard behavior, just a [well documented](https://cmake.org/cmake/help/v3.0/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) CMake option. However, I have seen it done in OpenSSL and gRPC.

**Comment by isaachier** [comment]
The reason Jaeger does it is to allow linking a shared object from the static archive. I would consider switching that out, but the downsides seem rather vague (potential slowdown, unclear how significant).
