### ISSUE TITLE
bool return for Finish to indicate dropped Span

### ISSUE THREAD

**Issue by MarkKMueller** [opentracing/opentracing-cpp#52]
Currently there is no means to know if a span gets dropped, or has some sort of failure - Finish is a void return function. I would like to submit a PR that adds a bool return type to Finish and FinishWithOptions.

What is the likely hood of that being accepted?

**Comment by rnburn** [comment]
One problem is that you don't necessarily know after finish returns whether it will be dropped or not.

Many tracer implementations buffer the span and periodically send them to a collector, so you wouldn't know until they're sent whether they were successfully collected.

opentracing-cpp for the most part follows the conventions in the other languages (which don't return anything on Finish). You might try raising the issue on https://gitter.im/opentracing/public to see if there's any interested in developing some sort of cross-language api to give access to metrics data like dropped spans.

**Comment by MarkKMueller** [comment]
OK, in this case, we are concerned about the case where the buffer itself is full so that we can take action on that, not whether they are successfully collected down the line.

My original approach was to add a new function that can be called which will return the number of spans dropped over a time period, with an option to reset the count and time, or leave it as is. Would that receive a better reception than modifying finish?

**Comment by yurishkuro** [comment]
what would you do in such callback function?  If your goal is merely knowing that the tracer is dropping spans, then the (good) tracers would typically expose some metrics API.

**Comment by MarkKMueller** [comment]
It wouldn't be a call back, just a function to call that would return a count of how many spans were dropped because there was no room in the span buffer, or some other reason that it was known to be dropped in that part of the pipe.

So, for instance, every minute I could call that function to retrieve the number of spans that didn't make it to the span buffer over the last minute, and then report that information somewhere, or take action if it 
there is a problem

**Comment by yurishkuro** [comment]
this is essentially what metrics do. E.g.

https://github.com/jaegertracing/jaeger-client-go/blob/55f3f0a2fa077e251449eef761097d683b4e9866/metrics.go#L53-L54

We generally left this concern to Tracer implementation, rather than adding an introspection API to OpenTracing.

**Comment by MarkKMueller** [comment]
OK. Fair enough. With zipkin-cpp-opentracing, the Tracer implementation is opaque making the information currently impossible to get. Thus it looks like I need to take this matter up with them.

Thanks for your help with this!
