### ISSUE TITLE
string_view error

### ISSUE THREAD

**Issue by wolfelven** [opentracing/opentracing-cpp#70]
according to tutorial, when i include <opentracing/mocktracer/json_recorder.h>, reporting some errors
In file included from /usr/local/include/opentracing/mocktracer/json_recorder.h:4:
In file included from /usr/local/include/opentracing/mocktracer/recorder.h:4:
In file included from /usr/local/include/opentracing/tracer.h:4:
In file included from /usr/local/include/opentracing/propagation.h:4:
/usr/local/include/opentracing/string_view.h:55:16: error: expected ';' at end of declaration list
  string_view() noexcept : data_(nullptr), length_(0) {}
               ^
/usr/local/include/opentracing/string_view.h:96:58: error: expected function body after function declarator
inline bool operator==(string_view lhs, string_view rhs) noexcept {
                                                         ^
In file included from ../src/HelloWorld.cpp:2:
In file included from /usr/local/include/opentracing/mocktracer/json_recorder.h:4:
In file included from /usr/local/include/opentracing/mocktracer/recorder.h:4:
In file included from /usr/local/include/opentracing/tracer.h:4:
In file included from /usr/local/include/opentracing/propagation.h:5:
In file included from /usr/local/include/opentracing/util.h:13:
/usr/local/include/opentracing/expected/expected.hpp:105:5: error: unknown type name 'constexpr'
    constexpr value_type const & value() const &
    ^
/usr/local/include/opentracing/expected/expected.hpp:105:15: error: duplicate member 'value_type'
    constexpr value_type const & value() const &
              ^
/usr/local/include/opentracing/expected/expected.hpp:68:15: note: previous declaration is here
    typedef T value_type;
              ^
/usr/local/include/opentracing/expected/expected.hpp:105:25: error: expected ';' at end of declaration list
    constexpr value_type const & value() const &
                        ^
/usr/local/include/opentracing/expected/expected.hpp:77:15: error: use of undeclared identifier 'm_value'
        new( &m_value ) value_type( v );
              ^
/usr/local/include/opentracing/expected/expected.hpp:82:15: error: use of undeclared identifier 'm_value'
        new( &m_value ) value_type( std::forward<T>( v ) );
              ^
/usr/local/include/opentracing/expected/expected.hpp:87:9: error: use of undeclared identifier 'm_value'
        m_value.~value_type();
        ^
/usr/local/include/opentracing/expected/expected.hpp:204:5: error: unknown type name 'constexpr'
    constexpr explicit unexpected_type( error_type const & error )
    ^
/usr/local/include/opentracing/expected/expected.hpp:204:15: error: expected member name or ';' after declaration specifiers
    constexpr explicit unexpected_type( error_type const & error )
    ~~~~~~~~~ ^
/usr/local/include/opentracing/expected/expected.hpp:271:1: error: unknown type name 'constexpr'
constexpr bool operator==( unexpected_type<E> const & x, unexpected_type<E> const & y )
^
/usr/local/include/opentracing/expected/expected.hpp:271:11: error: expected unqualified-id
constexpr bool operator==( unexpected_type<E> const & x, unexpected_type<E> const & y )
          ^
/usr/local/include/opentracing/expected/expected.hpp:332:8: error: explicit specialization of non-template struct 'is_unexpected'
struct is_unexpected< unexpected_type<E> > : std::true_type {};
       ^            ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/opentracing/expected/expected.hpp:337:18: error: 'auto' not allowed in function return type
nsel_constexpr14 auto
                 ^~~~
/usr/local/include/opentracing/expected/expected.hpp:338:25: error: expected ';' at end of declaration
make_unexpected( E && v) -> unexpected_type< typename std::decay<E>::type >
                        ^
/usr/local/include/opentracing/expected/expected.hpp:338:26: error: cannot use arrow operator on a type
make_unexpected( E && v) -> unexpected_type< typename std::decay<E>::type >
                         ^
/usr/local/include/opentracing/expected/expected.hpp:344:42: error: expected function body after function declarator
make_unexpected_from_current_exception() -> unexpected_type< std::exception_ptr >
                                         ^
/usr/local/include/opentracing/expected/expected.hpp:353:1: error: unknown type name 'constexpr'
constexpr in_place_t in_place{};
^
/usr/local/include/opentracing/expected/expected.hpp:353:21: error: expected ';' after top level declarator
constexpr in_place_t in_place{};
                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [src/HelloWorld.o] Error 1

**Comment by rnburn** [comment]
It looks like you're compiling without C++11 support turned on.

Could you confirm which compiler and version you're using and whether you have `-std=c++11` set?

**Comment by wolfelven** [comment]
@rnburn Thanks .But when i and c++11 in eclipse(Mac OS), new errors:
Building target: ProjectTest
Invoking: MacOS X C++ Linker
g++  -o "ProjectTest"  ./src/HelloWorld.o   
Undefined symbols for architecture x86_64:
  "opentracing::v1::propagation_error_category()", referenced from:
      ___cxx_global_var_init in HelloWorld.o
      ___cxx_global_var_init.1 in HelloWorld.o
      ___cxx_global_var_init.2 in HelloWorld.o
      ___cxx_global_var_init.3 in HelloWorld.o
      ___cxx_global_var_init.4 in HelloWorld.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ProjectTest] Error 1

**Comment by rnburn** [comment]
you need to add the flags to link against it "-lopentracing"

**Comment by rnburn** [comment]
Closing. If you have questions about how to set up the build, you can ask on https://gitter.im/opentracing/opentracing-cpp.
