### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wolfelven** [opentracing/opentracing-cpp#73]
My main code :
auto config = jaegertracing::Config(
	      false,
	      jaegertracing::samplers::Config(jaegertracing::kSamplerTypeConst, 1),
	      jaegertracing::reporters::Config(
	          jaegertracing::reporters::Config::kDefaultQueueSize,
	          std::chrono::seconds(1), true));
	std::shared_ptr<opentracing::Tracer> tracer = jaegertracing::Tracer::make("c++", config);
	  auto span = tracer->StartSpan("abc");
	  std::this_thread::sleep_for(std::chrono::milliseconds{10});
	  span->Finish();
	  std::this_thread::sleep_for(std::chrono::seconds{5});
	  tracer->Close();

then build error is :
clang++ -D__GXX_EXPERIMENTAL_CXX0X__ -D__cplusplus=201103L -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -stdlib=libc++ -MMD -MP -MF"src/jaegertracing/thrift-gen/Agent.d" -MT"src/jaegertracing/thrift-gen/Agent.o" -o "src/jaegertracing/thrift-gen/Agent.o" "../src/jaegertracing/thrift-gen/Agent.cpp"
../src/jaegertracing/thrift-gen/Agent.cpp:70:10: error: no member named 'incrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'incrementInputRecursionDepth'?
  oprot->incrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         incrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:557:8: note: 'incrementInputRecursionDepth' declared here
  void incrementInputRecursionDepth() {
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:87:10: error: no member named 'decrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'decrementInputRecursionDepth'?
  oprot->decrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         decrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:562:8: note: 'decrementInputRecursionDepth' declared here
  void decrementInputRecursionDepth() { --input_recursion_depth_; }
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:98:10: error: no member named 'incrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'incrementInputRecursionDepth'?
  oprot->incrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         incrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:557:8: note: 'incrementInputRecursionDepth' declared here
  void incrementInputRecursionDepth() {
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:115:10: error: no member named 'decrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'decrementInputRecursionDepth'?
  oprot->decrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         decrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:562:8: note: 'decrementInputRecursionDepth' declared here
  void decrementInputRecursionDepth() { --input_recursion_depth_; }
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:166:10: error: no member named 'incrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'incrementInputRecursionDepth'?
  oprot->incrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         incrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:557:8: note: 'incrementInputRecursionDepth' declared here
  void incrementInputRecursionDepth() {
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:175:10: error: no member named 'decrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'decrementInputRecursionDepth'?
  oprot->decrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         decrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:562:8: note: 'decrementInputRecursionDepth' declared here
  void decrementInputRecursionDepth() { --input_recursion_depth_; }
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:186:10: error: no member named 'incrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'incrementInputRecursionDepth'?
  oprot->incrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         incrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:557:8: note: 'incrementInputRecursionDepth' declared here
  void incrementInputRecursionDepth() {
       ^
../src/jaegertracing/thrift-gen/Agent.cpp:195:10: error: no member named 'decrementRecursionDepth' in 'apache::thrift::protocol::TProtocol'; did you mean 'decrementInputRecursionDepth'?
  oprot->decrementRecursionDepth();
         ^~~~~~~~~~~~~~~~~~~~~~~
         decrementInputRecursionDepth
/usr/local/include/thrift/protocol/TProtocol.h:562:8: note: 'decrementInputRecursionDepth' declared here
  void decrementInputRecursionDepth() { --input_recursion_depth_; }
       ^
8 errors generated.
make: *** [src/jaegertracing/thrift-gen/Agent.o] Error 1

my local thrift version is 0.9.3

**Comment by rnburn** [comment]
This looks like a jaeger build issue. This repo's only for the OpenTracing API. Could you please ask instead on https://gitter.im/jaegertracing/Lobby.
