### ISSUE TITLE
Macos gcc/clang error

### ISSUE THREAD

**Issue by wolfelven** [opentracing/opentracing-cpp#76]
Hello, everyone.When i use Eclipse to build c++ code ,that is ok.But in terminal there is link error.

clang++ -std=c++11 AMQPClientSend.cpp -o send -lSimpleAmqpClient -lopentracing -lcurl -ljaegertracing -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name AMQPClientSend.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 274.1 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0 -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/xujie/Desktop/C_Project/AMQP_Opentrainc/src -ferror-limit 19 -fmessage-length 117 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/8h/yw85sq4j5mjf9q19rm24vv340000gn/T/AMQPClientSend-b52538.o -x c++ AMQPClientSend.cpp
clang -cc1 version 8.0.0 (clang-800.0.42.1) default target x86_64-apple-darwin15.6.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
/usr/local/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
/usr/include
/System/Library/Frameworks (framework directory)
/Library/Frameworks (framework directory)
End of search list.
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o send /var/folders/8h/yw85sq4j5mjf9q19rm24vv340000gn/T/AMQPClientSend-b52538.o -lSimpleAmqpClient -lopentracing -lcurl -ljaegertracing -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
"TraceSingleton::getInstance()", referenced from:
CreateTrace(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) in AMQPClientSend-b52538.o
"TraceSingleton::CreateTracer(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, opentracing::v1::Value, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, opentracing::v1::Value> > >, std::initializer_list<std::__1::pair<opentracing::v1::string_view, opentracing::v1::Value> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > >, DHTracer*)", referenced from:
CreateTrace(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) in AMQPClientSend-b52538.o
"TraceSingleton::SendContextWithRequest()", referenced from:
CreateTrace(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) in AMQPClientSend-b52538.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rnburn** [comment]
Please use this only for actual issues with the OpenTracing-C++ API or library. It isn't the right place to get general help to set up a C++ build environment.

**Comment by wolfelven** [comment]
@rnburn Thanks。The reason is I forgot to compile with other cpps.
btw, Do you konw why I need to use "this_thread::sleep_for(sometime)" after span is finished().
Code:
if(parCtx == NULL){
		cout << "NUll" << endl;
		activeSpan = tracer->StartSpan(spanName); //, {opentracing::ChildOf(&(activeSpan->context()))}
	}else{
		cout << "Not NUll" << endl;
		activeSpan = tracer->StartSpan(spanName, {opentracing::ChildOf(parCtx)});
	}
	setSpanInfo(tagOptions, logOptions);
	activeSpan->Finish();
	std::this_thread::sleep_for(std::chrono::seconds{2});

**Comment by rnburn** [comment]
If you close the tracer, you shouldn't need that sleep statement. But it looks like you already made an issue for this: https://github.com/jaegertracing/jaeger-client-cpp/issues/79

**Comment by wolfelven** [comment]
@rnburn Yes，i made an other issue.But I still don't understand the relationship between with Finish() and sleep. In code, I don't close the tracer. If i noly use span.finish(), the span don't send to the agent. When add sleep, the span show in UI.
