### ISSUE TITLE
Confusion over how to best declare a tracer

### ISSUE THREAD

**Issue by gabrielkay** [opentracing/opentracing-cpp#84]
I'm just trying to make a span and have that span log a few values then close. I'm pretty sure my span code is fine, I just don't know how to declare a tracer than will send traces to my localhost:9411 (run through docker). I've tried declaring a MockTracer with default constructed options and an auto constructed NoopTracer but when I run nothing shows up on the zipkin api. It would be a huge help if you could tell me how I can declare a basic tracer (which was never fully addressed in any of the specs) and if I need to make any calls to make sure my traces are sent out to the localhost.

**Comment by rnburn** [comment]
opentracing-cpp is an API for tracers. It doesn't include tracer implementations other than the mocktracer (which is meant for testing).

If you're looking for an open-source implementations, check out the [Jaeger](https://github.com/jaegertracing/jaeger-client-cpp) and [Zipkin](https://github.com/rnburn/zipkin-cpp-opentracing) repositories.

**Comment by gabrielkay** [comment]
I'm using it with your zipkin repository. Are there no calls in this API that initialize a zipkin tracer from that repository? Or should I use the syntax of the zipkin repository. Thanks!

**Comment by rnburn** [comment]
You can either construct the tracer by directly calling its API functions or you can dynamically load a tracer dynamically from JSON.

See https://github.com/rnburn/ot-chat for a dynamic loading example.

**Comment by gabrielkay** [comment]
Using the zipkin-cpp-opentracing syntax worked. I'd recommend adding a little more info to the README as @yurishkuro said above. Other then that you can close/delete this. Thanks for the help.
