### ISSUE TITLE
i want use Opentracing-cpp in my My Project

### ISSUE THREAD

**Issue by sureshbalakundi** [opentracing/opentracing-cpp#9]
i want use Opentracing-cpp in my My Project. please give me some some sample cpp example. I already Installed opentracing library in Linux system

**Comment by lookfwd** [comment]
You can't use opentracing-c++ as it is, right now, for anything useful to you. Join the discussions [here](https://github.com/opentracing/opentracing-cpp/pull/7) and in [gitter](gitter.im/opentracing/opentracing-cpp) and you will see if there's any progress.
