### ISSUE TITLE
Adding functionality to package this repo into rpms for centos and fedora users

### ISSUE THREAD

**Issue by gabrielkay** [opentracing/opentracing-cpp#95]
~~I'm building this repository into an RPM, and the only issue I'm having is including version.h in the rpm. It seems version.h is made from version.h.in, but I can't figure out what is turning version.h.in into version.h and it isn't happening just from the make.~~

Sorry, I resolved my issue above. I made changes so that running `make rpm` in .build/ now makes two rpms (one with .so's and one with headers). I also implemented this with your zipkin repository. I can contribute these to github if any centos or fedora users want to package opentracing as an rpm. It's just an addition to the CMakeList.txt and two additional .spec files. Let me know if I can contribute this and I'll push it.
Thanks!

**Comment by rnburn** [comment]
Yes, support for packaging would be welcome.

Are you planning to add these to any RPM repositories? Is there a way we could set up CI/CD for it?

**Comment by gabrielkay** [comment]
Wasn't planning on adding it to any rpm repositories. I tried to push my code and make it a pull request but it looks like pushes are restricted on this repo. Let me know how I can push so you can check if this should be added. I can also push the same changes for your zipkin-cpp-opentracing repo.

**Comment by rnburn** [comment]
You can fork the repo. Push it to your fork. Then submit a pull request.

Take a look at the documentation [here](https://help.github.com/articles/fork-a-repo/) for more detailed instructions.
